---

- name: local pacakges management
  hosts: localhost
  gather_facts: true
  collections:
    - community.general

  tags:
    - packlocal
    - never
  
  tasks:

    - name: Needed packages on system
      include_tasks: packlocal.yml


- hosts: localhost
  name: vcenter fips mode
  gather_facts: False
  vars:
    changefipsmode: false
    fipsmode: false
    var_vcenter_hostname: "10.93.60.138"
    var_vcenter_username: "administrator@vsphere.local"
    var_vcenter_password: "{{ lookup('ansible.builtin.env', 'VCPASSWORD') }}"

  collections:
    - community.general
    - community.vmware
    - vmware.vmware_rest

  module_defaults:
    group/vmware:
      hostname: "10.93.60.138"
      username: "administrator@vsphere.local"
      password: "{{ lookup('ansible.builtin.env', 'VCPASSWORD') }}"
      validate_certs: false

  tasks:

    - name: Host mode
      include_tasks: fips.yml

